### ISSUE TITLE
Testnet guide document is obsolete

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#101]
![4D6BF53B-1411-43DC-ADCC-3B904BB35402](https://user-images.githubusercontent.com/84637156/186480454-084a7a83-22a0-4657-81b0-225b244d405b.jpeg)

the link to the wall-thru guide will not make sense on mainnet lets just remove until we have an updated version for mainnet

**Comment by fisherstevenk** [comment]
Worked in #100
