### ISSUE TITLE
Add Reward calcs to explore menu

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#104]
can we put this in Explore Menu next to Pools? so we can list current calculations we have in the system?

REWARD CALCULATIONS

Custom FreeLoaderz
1) tFLZ: (S-150)^0.6 + 50.0 = R; where S=Staked amount to participating pool and P=tFLZ payout per epoch
More info here https://freeloaderz.medium.com/freeloaderz-pspo-9d1df5fdadc2

Custom Drasil
2) tDRSL: Total staked to all participating pools. 10,000 / TS * S = P where TS = Total Staked in all pools, S=Stake of Claiming wallet, P=tDRSL payout per epoch

Fixed Ratio
3) tCDN: 0.3 * S = P; where S=Stake of Claiming Wallet, P=Payout of tCDN per epoch

**Comment by fisherstevenk** [comment]
Worked in #100
