### ISSUE TITLE
Claim Fees FAQ and TOS

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#107]
Price and Payments
The user withdrawing tokens from SmartClaimz will be charged a 2A service fee. The service fee covers the processing costs on SmartClaimz.  The UTXO minimum fee will be automatically calculated and added. Please be sure to confirm that you are withdrawing to your own address. All token withdrawals are final and can not be reversed.

**Comment by fisherstevenk** [comment]
Worked in #100
