### ISSUE TITLE
Testnet Guide is old

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#108]
Please remove the sentence and link from the FAQ. We will work on a new one for Mainnet.

**Comment by EtherealStakePool** [comment]
Please use this if you'd like! I updated it for Preview Mode if we want to get more people testing it.

https://docs.google.com/document/d/1cGkCN7Go0Q1tQchBzcI-7-QqQlAVeloDg_j3OqdTabY/edit?usp=sharing

**Comment by fisherstevenk** [comment]
Worked into #100
