### ISSUE TITLE
Clicking on the URL in FLZ Token Display error

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#118]
/explore/tokens/FLZ
Clicking on the URL in FLZ Token Display error

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<script/>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>3Z3AXJHRNABPP6Q2</RequestId>
<HostId>pe3Ngtzbz66eILcgTe/DYbOpF4Cd+/6yq4ny/KcDwXuIS8iGscn8GWvPRN+CmC58igirIjmmNOU=</HostId>
</Error>

**Comment by fisherstevenk** [comment]
Clear your cache..

**Comment by santonode** [comment]
> Clear your cache..

iphone13 IOS cleared cache still error

AccessDeniedAccess DeniedMZEM4ET54BG90TRY8RIQ9cTVJtHWWZQYVYCUy/7xq33haIzM+WOluPAG8gXsH6OxM+Cej3lAGoqNbRILSdAg8rgtSbc=

**Comment by fisherstevenk** [comment]
Go to https://smartclaimz.io not a page reload.  The page works

It's an amplify issue

**Comment by fisherstevenk** [comment]
![Uploading Screenshot_20220924-211625_Brave.jpg…]()

**Comment by santonode** [comment]
![Uploading 858660AD-85BA-416B-A7A7-CA55ED033DE7.jpeg…]()

**Comment by fisherstevenk** [comment]
/explore/tokens/FLZ

That isn't a valid url anyway.. where did you get that url?

Unless you mean 

Click Explore menu-> click Tokens -> click Find Pools for FLZ

**Comment by santonode** [comment]
yes click on the url i expect to go to freeloaderz.io

**Comment by fisherstevenk** [comment]
You do..  i just did it. 

![Uploading Screenshot_20220924-212306_Brave.jpg…]()

**Comment by santonode** [comment]
![F8EAFD99-2A72-4FFE-B9B6-742C9170CC55](https://user-images.githubusercontent.com/84637156/192124314-f2be12ba-2adc-4488-bad3-f4699475ccf8.jpeg)

**Comment by fisherstevenk** [comment]
I see what you are talking about now.   It wasn't clear

**Comment by santonode** [comment]
clear as mud

**Comment by fisherstevenk** [comment]
All good man!

Fixed URL reference #119
