### ISSUE TITLE
You always claiming all rewards no matter of the selection 

### ISSUE THREAD

**Issue by Sbcdn** [FreeLoaderz/rwd-frontend#14]
The Reward Claiming now works! Awesome!

I tried to claim just one of the 3 available tokens for me but it claimed all three in the transaction. 
(In the parameters  all three tokens are added and not just the ones I marked )

![image](https://user-images.githubusercontent.com/81830852/162473727-fcf398e5-3fd4-419b-8c21-e9dc676e8352.png)

**Comment by fisherstevenk** [comment]
https://github.com/FreeLoaderz/rwd-frontend/pull/12/commits/a4915cd5d1ea4fe84cbbdd7ca97d0bfe5a22a1e3
