### ISSUE TITLE
412 Error Response on Claim

### ISSUE THREAD

**Issue by kthedges12** [FreeLoaderz/rwd-frontend#151]
Looks like a POST request hitting this endpoint https://smartclaimz.io/rwdbuild/ms/fn/sporwc/e582972467e33521d088dac4a286315c8e68f8faa498adcfffa66f85 is what is causing a 412 response

**Comment by fisherstevenk** [comment]
This was an error on signature submission.  The last part of the URL is part of the signature.  It's possible something was down at that time.  If it ALWAYS fails for your wallet, try doing one token at a time.. if it always fails for your wallet and every single token, then we might need to check our wallet settings and have @Sbcdn  take a look at the back end.

**Comment by kthedges12** [comment]
Things are resolved, it was a temporary thing with no changes needed, closing this out.
