### ISSUE TITLE
Blue Submit Claimz

### ISSUE THREAD

**Issue by Blockjock** [FreeLoaderz/rwd-frontend#21]
After clicking claim token and the blue “submit clains” cones up can we make it Submit Claimz instead or is it hokey? Idk follows our SmartClaimz name I guess. Simple thing but

**Comment by fisherstevenk** [comment]
If we do this, we have to make sure it's not a one off and that it's used throughout the app.  Then it'll work

**Comment by Sbcdn** [comment]
I do not get this :)

**Comment by fisherstevenk** [comment]
Oh.. i did this already.  I should've closed this. 

On the rewards page, when you select at least one token, the "Submit Claimz" button shows up.

**Comment by Blockjock** [comment]
thanks Steve!
