### ISSUE TITLE
Generate/ rewards button n submit claimz button

### ISSUE THREAD

**Issue by Blockjock** [FreeLoaderz/rwd-frontend#22]
What if when you click the above mentioned buttons the button field started to fill a different color giving us the indicator we want while also looking cool:-) maybe make it look like water filling up from left to right or bottom to top.

**Comment by Sbcdn** [comment]
@fisherstevenk can we implement something like this as a "waiting effect" ? 
But if the effort is too large we prospone it, no prio.

**Comment by fisherstevenk** [comment]
It can be done.. here's an example:

https://webdevtrick.com/css-water-filling-text/

https://webdevtrick.com/demos/water-filling-text/

I would stay away unless we were creating some kind of water theme.  It looks cool, but it would be out of place with the current setup.

One other thing to keep in mind, I don't know how long a task on the backend will take to complete, so you couldn't use it like a progress bar.

**Comment by Blockjock** [comment]
yep of the two the second one that doesnt look like water could be cool but we could do it in blue instead of white. Anything that makes a bit more interactive and also gives the user a idea something is happening.

**Comment by fisherstevenk** [comment]
gonna close this one since we have the spinning icon.

If we get a mascot, then we can set up a theme.

**Comment by Blockjock** [comment]
Sounds good working on it now

James E Meidinger
Millennium Vending
