### ISSUE TITLE
Various ui/ux ideas

### ISSUE THREAD

**Issue by Blockjock** [FreeLoaderz/rwd-frontend#23]
3. In history “search field is square should be rounded
4. In history column headers should be blue
5. Submit claimz should have our asterisk to left “maybe” (design flare)
6. After signing instead of the white circling Indicator make our asterisk logo indicator circling in clock wise motion

**Comment by fisherstevenk** [comment]
👊😎

**Comment by fisherstevenk** [comment]
Verify this works the way we want.

Change is loaded on the server with this PR:
https://github.com/FreeLoaderz/rwd-frontend/pull/34
