### ISSUE TITLE
Claim request - no wallet connected

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#28]
I tried to make a claim with eternl wallet, but my dApp connector was not enabled (green dot) the UI did not give me an error are any kind of warning it said my claim was processing then no further guidance - should check to make sure my wallet is connected

**Comment by fisherstevenk** [comment]
Ah... yes.  I know the issue and what to fix. 

Thank you for reporting.

**Comment by fisherstevenk** [comment]
Verify this works the way we want.

Change is loaded on the server with this PR:
https://github.com/FreeLoaderz/rwd-frontend/pull/34
