### ISSUE TITLE
"Submit Claims" button disappear after an error

### ISSUE THREAD

**Issue by ADA-MASTER** [FreeLoaderz/rwd-frontend#29]
After an error the "Submit Claims" button disappear and have a bug getting it back. (see video)
[https://monosnap.com/file/wA7tfRrncEKh35KAQS4bfzI5e5DUPB](https://monosnap.com/file/wA7tfRrncEKh35KAQS4bfzI5e5DUPB)

**Comment by fisherstevenk** [comment]
Verify this works the way we want.

Change is loaded on the server with this PR:
https://github.com/FreeLoaderz/rwd-frontend/pull/34
