### ISSUE TITLE
FreeLoaderz Mascot

### ISSUE THREAD

**Issue by Blockjock** [FreeLoaderz/rwd-frontend#31]
Space Cowboy- a gunslingin space cowboy with a mechanical horse or something.

**Comment by Blockjock** [comment]
would be cool some sort of mascot that represented freeloaderz in a way everyone would recognize it. but its gotta be cool. This will be something promotional dept. will come up with.

**Comment by fisherstevenk** [comment]
I like the idea.  Could be a minor thing, but we have to be weary of the "pc police".. 😑
