### ISSUE TITLE
Connection reset by server

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#36]
Error: TX Submission Failed! connection reset by server
After claiming and inputting wallet signature, says signature accepted then got the above error

**Comment by Sbcdn** [comment]
Please more info, is not debuggable

**Comment by santonode** [comment]
I think this was same issue with AWS Gateway, I will try to replicate

**Comment by santonode** [comment]
Still Same error - it feels like something is out of sync. shows available rewards to claim, but I think I already claimed these rewards in past because the same amounts and tokens show in my rewards history 

Error TX Submission Failed! connection reset by server

**Comment by Sbcdn** [comment]
Are you trying to claim tMin Tokens in the group? This is not possible the script has not enough on it anymore. If so please deselect tMin and claim the rest. 
Can you please make some screenshots and copy here (just copy paste them into the text box github is smart :) )
Helpful is always: 
- the rewards overview
- the signature window from eternl / flint / gero (Nami is useless to little info)
- any extra infos you think are also helpful e.g. screenshot of the browser console

**Comment by santonode** [comment]
![temp](https://user-images.githubusercontent.com/84637156/163734011-2a8152f1-8057-4365-8f00-4485108b7bd5.png)
![temp](https://user-images.githubusercontent.com/84637156/163734044-ae628925-7ae3-4233-a485-27ff5799c4c3.png)
![temp](https://user-images.githubusercontent.com/84637156/163734102-5da2bc58-9dee-4e07-91cc-b337d6436d61.png)

**Comment by Sbcdn** [comment]
Can oyu show me the lower part of the signature window with the tokens ?

**Comment by Sbcdn** [comment]
I just claimed the same amount of the same token with success

**Comment by santonode** [comment]
![temp](https://user-images.githubusercontent.com/84637156/163734261-76206716-32a1-494e-98fd-7f7dda7b7ef2.png)

**Comment by Sbcdn** [comment]
Asset wasn't correctly added when a policy already existed on the output value, should be fixed now please retest and if it works close the ticket. 
Thank you!

**Comment by santonode** [comment]
TX Successfully transmitted!
[2cf43104f38e69d14844a10ff6d6e50a23ec90465f0bed549896489ce425dc49](https://testnet.cardanoscan.io/transaction/2cf43104f38e69d14844a10ff6d6e50a23ec90465f0bed549896489ce425dc49)
