### ISSUE TITLE
Nami Testnet Airdrop hangs

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#39]
I setup a Nami wallet, added 1000 tAda was able to connect, but choosing Testnet and trying to claim airdop 
Http failure response for https://rwd.freeloaderz.io/rwdbuild/multisig/1/testrewards: 503 Service Unavailable

**Comment by Sbcdn** [comment]
Somehow one of the gateway server got stuck on aws status checks and was not reachable anymore, I spooled up a new gateway server all fine now, need to observe if this happens again
