### ISSUE TITLE
Cant Claim Rewards

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#40]
It looks like the two tokens I have already claimed is still showing on my screen when I try to claim them nothing happens after about 5 minutes I get this error: Http failure response for https://rwd.freeloaderz.io/rwdbuild/multisig/1/sporwc: 503 Service Unavailable

![temp](https://user-images.githubusercontent.com/84637156/163717904-16024c38-413b-4c4c-b572-20a158d803e0.png)

**Comment by Sbcdn** [comment]
Somehow one of the gateway server got stuck on aws status checks and was not reachable anymore, I spooled up a new gateway server all fine now, need to observe if this happens again
