### ISSUE TITLE
Collateral Error

### ISSUE THREAD

**Issue by fisherstevenk** [FreeLoaderz/rwd-frontend#41]
Add additional information for users to fix the collateral error. 

![Screenshot_2022-04-18_9 08 40_AM](https://user-images.githubusercontent.com/86887231/163838397-71342ddf-03ed-4a5f-9d23-b18ee804da39.png)

**Comment by Sbcdn** [comment]
We should create a FAQ site and link in the error messages to this FAQ articles

**Comment by fisherstevenk** [comment]
I created a bounty for that but no one seems to wants to take up the faq..

**Comment by fisherstevenk** [comment]
@kthedges12 This can be the start of a new FAQ section.

It should be it's own nav bar menu item that's viewable whether you are connected or not.
