### ISSUE TITLE
Fix Mobile View for Contact Us

### ISSUE THREAD

**Issue by kthedges12** [FreeLoaderz/rwd-frontend#49]
The Contact Us form expands the screen on mobile version and the FAQ section toggle feature is not working

**Comment by fisherstevenk** [comment]
FAQ was re-written so it works on mobile.  There seems to be a primeng bug for mobile so I had to scrap the whole thing and re-write it.

**Comment by fisherstevenk** [comment]
ngAfterViewInit and ngAfterContentInit were not being called.. so I had to implement a sleep/timeout to load the buttons

**Comment by fisherstevenk** [comment]
https://github.com/FreeLoaderz/rwd-frontend/commit/dd730f0e9ffdf1e56edfb822878636ca50bae116

Fixed and submit also works
