### ISSUE TITLE
LoadWarrior NFT info to help section

### ISSUE THREAD

**Issue by santonode** [FreeLoaderz/rwd-frontend#99]
can u add some info about loadwarrior nft to smartclaimz help section?

**Comment by fisherstevenk** [comment]
I can.. give me a write-up @santonode

**Comment by fisherstevenk** [comment]
SmartClaimz Fee Saver NFTs - LoadWarrior Series 1 (SOLD OUT)
LoadWarrior Series 1 - PolicyID 8cfa9a13c339f6d1e9fd3373698194e4a0b6da205c6f36cd1c324fcd 

If one of these NFTs is detected in user wallets, FreeLoaderz will apply three different claim fee discounts (10%, 25% or 50% depending on metadata value in the NFT). There will be 25 unique images with 10 variations (total quantity 250) of each image with the following metadata rarities: 

Quantity: 6 (10% discount) 

Quantity: 3 (25% discount)

Quantity: 1 (50% discount)

**Comment by fisherstevenk** [comment]
https://freeloaderz.medium.com/freeloaderz-pspo-9d1df5fdadc2

Freeloaderz PSPO — 7.5 Million FLZ Stake Pool Distribution
1) You stake to a participating Pool
2) You keep your normal ADA Staking rewards and get free FLZ
3) You claim your tokens on https://smartclaimz.io/
4) The amount of tokens eligible is based on your stake amount (see below)
5) You can claim every epoch or let them accumulate and claim later
6) The FLZ token allows you to vote on FreeLoaderz governance
7) Will last from September to December or when 7.5 Million is reached

**Comment by santonode** [comment]
Notice to all LoadWarrior NFT holders
We do not anticipate the fee discount functionality will be ready in September at launch. 

Option 1 
You can let your FLZ rewards accumulate and wait to claim your FLZ until this functionality is completed.
OR
Option 2
Claim now and not get the claim fee discount

Our recommendation is that wait because you can save way more in fees if you let them accumulate and claim all your FLZ rewards in October, November or December

**Comment by santonode** [comment]
any progress?

**Comment by fisherstevenk** [comment]
Worked into #100
